### ISSUE TITLE
Newest update makes Lua difficult to read

### ISSUE THREAD

**Issue by HaloDiehards** [LuaLS/lua.tmbundle#2]
Previous to the newest update, Lua code was easier to read. I am a developer of Core games and spend hours a day writing and editing code. Previously, variables were white and much easier to find in code. Now, they are the same color as properties, etc. This is makiing the code much harder to read, as it all blends together in a mess, and it makes it much more difficult to find things when debugging. Please revert!

**Comment by sumneko** [comment]
Thanks for your report, I will fix it.

**Comment by sumneko** [comment]
![image](https://user-images.githubusercontent.com/5213431/156831047-ef4a5ede-a819-4a94-beb4-d41ba23e48b4.png)

Please check if this can meet your need?

**Comment by sumneko** [comment]
I just published the fixed lua-grammar here: https://marketplace.visualstudio.com/items?itemName=sumneko.lua-grammar
You can install it and keep giving me feedback if there is anything to improve.
I'll submit improvements into VSCode as soon as possible.

**Comment by sammalt** [comment]
Hi, I believe the fixed grammar does not fix the issues depicted below? What is wrong there IMO:

1. the function name in the declaration and the function callsites have the same color - pretty sure this didn't use to be the case..? See function foo and the callsite.
2. standard modules such as table and string have some sort of special treatment, which results in problems like depicted - string is colorized differently from other functions. I don't think the built-in modules should be special cased, because you don't have to open them by default. My example is contrived, but we actually had a real world use-case where this showed up.

![Code_SCbvesKzQ9](https://user-images.githubusercontent.com/26298124/157195219-1503aeff-b3c1-4394-b9cf-c2523b8990ad.png)

**Comment by sumneko** [comment]
@sammalt let's move to another issue

**Comment by sumneko** [comment]
This fix will be released by next version of VSCode, closing.

**Comment by HaloDiehards** [comment]
I got a Visual Studio Code update, but the variables for Lua are all still the same color as the properties. It is so difficult to read that I am considering to stop using VSC and just use the default Core editor. Too much blue! Needs the white to be returned for variables, to break up the text and prevent so much blue. All of these should be white.
![image](https://user-images.githubusercontent.com/3395014/158024823-719f99db-3bf2-411f-a7d7-3f1ca58efdf2.png)

**Comment by sumneko** [comment]
> I got a Visual Studio Code update, but the variables for Lua are all still the same color as the properties.

This change will take effect in the next major version of VSCode, which should be version 1.66 around April 5th.
Fornow you can install this extension to take effect: https://marketplace.visualstudio.com/items?itemName=sumneko.lua-grammar
